sudo: reqired
language: generic
services:
  - docker

before_install
  - docker build -t syedwahed/react-test -f ./client/Dockerfile.dev ./client


 script:
  - docker run -e CI=true syedwahed/react-test npm test

  after_success:
    - docker build -t syedwahed/multi-client ./client
    - docker build -t syedwahed/multi-nginx ./nginx
    - docker build -t syedwahed/multi-server ./server
    - docker build -t syedwahed/multi-worker ./worker
# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  
# Tak

- docker push syedwahed/multi-client
- docker push syedwahed/multi-nginx
- docker push syedwahed/multi-server
- docker push syedwahed/multi-worker